name: API CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Write service account key
        env:
            FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KET }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Set runtime secret
        run: firebase functions:config:set jwt.secret="${{ secrets.JWT_SECRET }}" --project $PROJECT_ID --token "${{ secrets.FIREBASE_CI_TOKEN }}"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy Cloud Functions
        env:
            GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
        run: firebase deploy --only functions,hosting --project $PROJECT_ID

    env:
      NODE_VERSION: 20
      PROJECT_ID: tasks-collection-82ded
      GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json